### ISSUE TITLE
What's the actual licensing cost? one time 15$ or monthly 30$

### ISSUE THREAD

**Issue by krtschmr** [TypoCI/spellcheck-action#112]
30$ a month:
https://github.com/marketplace/typo-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW42MTMx#pricing-and-setup

15$ one time:
https://gumroad.com/l/MvvBE

i am confused what the cost of this actually is

**Comment by MikeRogers0** [comment]
It's a little confusing :/

> 15$ one time:

This is for the GitHub Action, which is [this repo](https://github.com/TypoCI/spellcheck-action) which is the library you can add to your GitHub Actions (e.g. `.github/workflows/spelling.yml`) within your repo. It's kind of limited & doesn't work for forks of repos.

> 30$ a month:

This is for the marketplace version of the app, which means you don't have to maintain a `.github/workflows/spelling.yml` file & it works for forks. It costs a bit more because it requires I run a server.

**Comment by MikeRogers0** [comment]
https://github.com/TypoCI/spellcheck-action/pull/119 - I'm removing the licensing requirements for the GitHub Action & I'm going to focus my efforts on the Marketplace app.
